const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.LESSON_BASE_URL||'http://127.0.0.1:8001',out=path.resolve(__dirname,'../../artifacts/learner-profiles');fs.mkdirSync(out,{recursive:true});
async function create(page,name){await page.locator('#learner-name').fill(name);await page.getByRole('button',{name:'Vào học ngay',exact:true}).click();await page.waitForFunction(n=>window.DanhLearners?.current?.name===n && !!document.querySelector('danh-learner'),name);}
async function add(page,name){await page.evaluate(()=>DanhLearners.open());await page.getByRole('button',{name:'+ Thêm người học',exact:true}).click();await create(page,name);}
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});try{
 const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await ctx.route('**/*',r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
 await page.addInitScript(()=>{if(!localStorage.getItem('test-seeded')){localStorage.setItem('test-seeded','1');localStorage.setItem('danh-g6-unit1','[1,2]');localStorage.setItem('f_logged','old@example.com');localStorage.setItem('f_users',JSON.stringify({'old@example.com':{password:'secret',reviewList:['el_1'],learnedList:['el_2'],customWords:[]}}));}});
 await page.goto(base+'/index.html',{waitUntil:"domcontentloaded"});await page.locator('#learner-name').waitFor();assert.equal(await page.evaluate(()=>DanhLearners.current),null);assert.ok(await page.locator('nav.container').evaluate(e=>e.inert));
 await page.screenshot({path:path.join(out,'first-visit-mobile.png'),fullPage:true});await create(page,'Minh');const minh=await page.evaluate(()=>DanhLearners.current.id);
 assert.equal(await page.evaluate(()=>DanhLearners.storage.getItem('danh-g6-unit1')),'[1,2]');assert.equal(await page.evaluate(()=>DanhLearners.storage.getItem('l_list_g')),'["el_2"]');
 await page.goto(base+'/grammar-practice.html?topic=present-simple',{waitUntil:"domcontentloaded"});await page.locator('#start-btn').click();await page.locator('#skip-btn').click();await page.locator('#next-btn').click();
 const round=await page.evaluate(()=>JSON.parse(DanhLearners.storage.getItem('danh-grammar-room-v1')).active);assert.equal(round.index,1);
 await page.evaluate(()=>{DanhLearners.storage.setItem('danh-grammar-experience-v1',JSON.stringify({sound:false,motion:false}));});
 await page.goto(base+'/index.html',{waitUntil:"domcontentloaded"});await add(page,'Hoa');const hoa=await page.evaluate(()=>DanhLearners.current.id);assert.notEqual(hoa,minh);
 assert.equal(await page.evaluate(()=>DanhLearners.storage.getItem('danh-g6-unit1')),null);assert.equal(await page.evaluate(()=>DanhLearners.storage.getItem('danh-grammar-room-v1')),null);
 await page.goto(base+'/grammar-practice.html?topic=be',{waitUntil:"domcontentloaded"});assert.match(await page.locator('#sound-toggle').innerText(),/bật/);await page.locator('#start-btn').click();
 const hoaRound=await page.evaluate(()=>JSON.parse(DanhLearners.storage.getItem('danh-grammar-room-v1')).active);
 const second=await ctx.newPage();second.on('pageerror',e=>errors.push(e.message));await second.goto(base+'/index.html',{waitUntil:"domcontentloaded"});assert.match(await second.locator('danh-learner h1').innerText(),/Hoa/);await second.getByRole('button',{name:'Đổi người học',exact:true}).click();await second.getByRole('button',{name:/🐱 Minh/}).click();await second.waitForFunction(()=>DanhLearners.current?.name==='Minh');
 assert.equal(await page.evaluate(()=>DanhLearners.current.name),'Hoa');await second.goto(base+'/grammar-practice.html',{waitUntil:"domcontentloaded"});await second.locator('#resume-btn').click();assert.equal(await second.evaluate(()=>JSON.parse(DanhLearners.storage.getItem('danh-grammar-room-v1')).active.index),1);assert.match(await second.locator('#sound-toggle').innerText(),/tắt/);
 // Switching preserves this document's pagehide snapshot in Hoa's scope.
 await add(page,'Nam');const nam=await page.evaluate(()=>DanhLearners.current.id);assert.equal(await page.evaluate(()=>DanhLearners.storage.getItem('danh-grammar-room-v1')),null);
 assert.equal(await page.evaluate(id=>JSON.parse(localStorage.getItem('danh-learner-data:'+id+':danh-grammar-room-v1')).active.id,hoa),hoaRound.id);
 assert.equal(await second.evaluate(()=>DanhLearners.current.id),minh);
 // Rename and export work without changing the ID or affecting other tabs.
 await page.evaluate(()=>DanhLearners.manage());await page.getByRole('button',{name:'✏️ Đổi tên / bạn đồng hành'}).click();await page.locator('#learner-name').fill('Nam An');await page.getByRole('button',{name:'Lưu thay đổi',exact:true}).click();await page.waitForFunction(()=>DanhLearners.current?.name==='Nam An' && !!document.querySelector('danh-learner'));assert.equal(await page.evaluate(()=>DanhLearners.current.id),nam);
 await page.evaluate(()=>DanhLearners.manage());const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'📥 Tải bản sao lưu',exact:true}).click()]);await download.saveAs(path.join(out,'backup.json'));assert.doesNotMatch(fs.readFileSync(path.join(out,'backup.json'),'utf8'),/password|secret|example.com/);
 await page.getByRole('button',{name:'Đóng ✕'}).click();await page.goto(base+'/flashcard.html',{waitUntil:"domcontentloaded"});assert.equal(await page.locator('input[type=password]').count(),0);await page.evaluate(()=>{markCard(true);});assert.ok(await page.evaluate(()=>JSON.parse(DanhLearners.storage.getItem('l_list_g')).length>0));
 // Fresh session asks again; normal refresh keeps the learner.
 await page.reload({waitUntil:"domcontentloaded"});assert.equal(await page.locator('danh-learner .overlay').isVisible(),false);await page.evaluate(()=>DanhLearners.endSession());await page.getByRole('button',{name:'Đúng rồi, vào học',exact:true}).waitFor();await page.screenshot({path:path.join(out,'confirm-mobile.png'),fullPage:true});await page.getByRole('button',{name:'Đúng rồi, vào học',exact:true}).click();await page.waitForFunction(()=>DanhLearners.current?.name==='Nam An');
 // Mobile chooser and all public study areas remain usable.
 for(const width of[320,375,390,430,844,1280]){await page.setViewportSize({width,height:900});await page.goto(base+'/index.html',{waitUntil:"domcontentloaded"});await page.evaluate(()=>DanhLearners.open());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'layout '+width);assert.ok(await page.locator('danh-learner .sheet').evaluate(e=>e.scrollWidth<=e.clientWidth),'dialog '+width);if(width===390)await page.screenshot({path:path.join(out,'choose-mobile.png'),fullPage:true});await page.getByRole('button',{name:'Đóng ✕'}).click();}
 for(const url of['grade/lop2/lop2.html','grade/lop4/lop4.html','grade/lop6/unit1.html','grade/lop7/unit1.html','ipa-theory.html','ipa-practice.html']){await page.goto(base+'/'+url,{waitUntil:"domcontentloaded"});assert.equal(await page.evaluate(()=>DanhLearners.current.name),'Nam An');}
 // Vocabulary marks from the actual lesson UI load only for the selected learner.
 await page.goto(base+'/grade/lop7/unit1.html',{waitUntil:'domcontentloaded'});
 await page.locator('[data-tab=quiz]').click();
 const correctMeaning=await page.evaluate(()=>{const text=document.querySelector('#quiz-stage h3').textContent;return DanhGrade7Units[0].words.find(w=>text.includes('“'+w.term+'”')).meaning;});
 await page.locator('#quiz-stage button').filter({hasText:correctMeaning}).click();assert.equal(await page.evaluate(()=>JSON.parse(DanhLearners.storage.getItem('danh-g7-unit1')).length),1);
 await page.reload({waitUntil:'domcontentloaded'});assert.match(await page.locator('#unit-progress').innerText(),/1\/8/);
 // Import is a separate profile, then deletion affects only the chosen name.
 await page.goto(base+'/index.html',{waitUntil:'domcontentloaded'});await page.evaluate(()=>DanhLearners.open());await page.getByRole('button',{name:'Khôi phục từ bản sao lưu',exact:true}).click();await page.locator('danh-learner input[type=file]').setInputFiles(path.join(out,'backup.json'));
 await page.waitForFunction(id=>DanhLearners.current && DanhLearners.current.id!==id && document.querySelector('danh-learner'),nam);
 const restored=await page.evaluate(()=>DanhLearners.current.id);assert.equal(await page.evaluate(()=>DanhLearners.current.name),'Nam An');assert.equal(await page.evaluate(()=>DanhLearners.storage.getItem('danh-g7-unit1')),null);
 await page.evaluate(()=>DanhLearners.manage());await page.getByRole('button',{name:'Xóa hồ sơ này',exact:true}).click();await page.getByRole('button',{name:'Xác nhận xóa hồ sơ',exact:true}).click();await page.getByRole('button',{name:'Đúng rồi, vào học',exact:true}).waitFor();assert.equal(await page.evaluate(id=>localStorage.getItem('danh-learner-info:'+id),restored),null);assert.ok(await page.evaluate(id=>localStorage.getItem('danh-learner-info:'+id),nam));
 await page.getByRole('button',{name:'Đúng rồi, vào học',exact:true}).click();await page.waitForFunction(()=>DanhLearners.current && document.querySelector('danh-learner'));
 // Same learner in two tabs receives a safe reload gate instead of stale writes.
 const third=await ctx.newPage();await third.goto(base+'/index.html',{waitUntil:"domcontentloaded"});await third.getByRole('button',{name:'Đổi người học',exact:true}).click();await third.getByRole('button',{name:/🐱 Minh/}).click();await third.waitForFunction(()=>DanhLearners.current?.name==='Minh');await third.evaluate(()=>DanhLearners.storage.getItem('danh-grammar-room-v1'));await second.evaluate(()=>DanhLearners.storage.setItem('danh-grammar-room-v1',DanhLearners.storage.getItem('danh-grammar-room-v1')+' '));await third.getByRole('button',{name:'Tải lại để tiếp tục'}).waitFor();await third.keyboard.press('Escape');assert.ok(await third.getByRole('button',{name:'Tải lại để tiếp tục'}).isVisible());
 assert.deepEqual(errors,[]);await ctx.close();
 // Completely blocked storage still supports a usable temporary learner.
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{for(const k of ['localStorage','sessionStorage'])Object.defineProperty(window,k,{get(){throw Error('blocked');}});});const bp=await blocked.newPage();await bp.goto(base+'/index.html',{waitUntil:"domcontentloaded"});await create(bp,'Tạm thời');await bp.reload({waitUntil:"domcontentloaded"});assert.equal(await bp.evaluate(()=>DanhLearners.current.name),'Tạm thời');assert.ok(await bp.locator('danh-learner #storage-warning').isVisible());await blocked.close();
 console.log('PASS: legacy migration; Minh/Hoa/Nam isolation; saved grammar rounds/settings; multi-tab switching and conflicts; rename/export/import/delete; flashcards and grade 7 vocabulary marks; session confirmation; six widths; grade 2/4/6/7 and IPA; blocked storage.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
