const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../../shared/learner-profile-core.js');
function memory(){const map=new Map();return {get length(){return map.size;},key(i){return [...map.keys()][i]??null;},getItem(k){return map.get(k)??null;},setItem(k,v){map.set(k,String(v));},removeItem(k){map.delete(k);}};}
function fixture(){const raw=memory();let n=0;return {raw,store:C.createStore(raw,()=>String(++n))};}
test('Duplicate names have independent stable IDs; renaming preserves only the correct learner',()=>{const {store}=fixture(),a=store.create(' Minh '),b=store.create('Minh');store.scope(a.id).setItem('danh-g6-unit1','[1,2]');store.scope(b.id).setItem('danh-g6-unit1','[3]');store.rename(a.id,'Hoa','🐰');assert.equal(store.scope(a.id).getItem('danh-g6-unit1'),'[1,2]');assert.equal(store.scope(b.id).getItem('danh-g6-unit1'),'[3]');assert.equal(store.get(a.id).name,'Hoa');assert.notEqual(a.id,b.id);});
test('Deleting one learner cannot delete another or resurrect data through a stale tab',()=>{const {raw,store}=fixture(),a=store.create('Minh'),b=store.create('Hoa'),old=store.scope(a.id);old.setItem('danh.test','1');store.scope(b.id).setItem('danh.test','2');raw.setItem('unrelated','safe');store.remove(a.id);old.setItem('danh.test','resurrect');assert.equal(old.getItem('danh.test'),null);assert.equal(store.scope(b.id).getItem('danh.test'),'2');assert.equal(raw.getItem('unrelated'),'safe');});
test('Legacy migration is one time, keeps originals and excludes credentials',()=>{const {raw,store}=fixture();raw.setItem('danh-g7-unit1','[4]');raw.setItem('f_logged','old@example.com');raw.setItem('f_users',JSON.stringify({'old@example.com':{password:'secret',customWords:[{word:'cat'}],reviewList:['el_1'],learnedList:['el_2']}}));raw.setItem('other','value');const a=store.create('Minh','🐱',true),b=store.create('Hoa','🐰',true);assert.equal(store.scope(a.id).getItem('danh-g7-unit1'),'[4]');assert.equal(store.scope(b.id).getItem('danh-g7-unit1'),null);assert.equal(raw.getItem('danh-g7-unit1'),'[4]');const backup=JSON.stringify(store.backup(a.id));assert.match(backup,/cat/);assert.doesNotMatch(backup,/secret|password|example.com|"other"/);});
test('Failed migration rolls back new records and leaves legacy data recoverable',()=>{const {raw,store}=fixture();raw.setItem('danh.one','1');raw.setItem('danh.two','2');const set=raw.setItem;raw.setItem=(k,v)=>{if(k.includes(':danh.two'))throw Error('quota');set(k,v);};assert.throws(()=>store.create('Minh','🐱',true));assert.deepEqual(store.list(),[]);assert.equal(raw.getItem('danh.one'),'1');assert.equal([...Array(raw.length)].map((_,i)=>raw.key(i)).some(k=>k.startsWith(C.DATA)),false);});
test('A backup imports as a new profile and rejects nonlearning keys / invalid formats',()=>{const {store}=fixture(),a=store.create('Minh');store.scope(a.id).setItem('danh:ipa-reflex:v1','[]');const b=store.restore(JSON.stringify(store.backup(a.id)));assert.notEqual(a.id,b.id);assert.equal(store.scope(b.id).getItem('danh:ipa-reflex:v1'),'[]');const malicious=store.backup(a.id);malicious.data['f_users']='{}';assert.throws(()=>store.restore(JSON.stringify(malicious)));assert.throws(()=>store.restore('{}'));assert.equal(store.list().length,2);});
test('Registry entries from separate store instances survive simultaneous creation',()=>{const raw=memory(),a=C.createStore(raw,()=> 'a'),b=C.createStore(raw,()=> 'b');a.create('Minh');b.create('Hoa');assert.equal(a.list().length,2);assert.equal(b.list().length,2);});
test('A locked tab cannot overwrite a newer round or settings',()=>{const {store}=fixture(),a=store.create('Minh'),old=store.scope(a.id),fresh=store.scope(a.id);old.getItem('danh-grammar-room-v1');old.lock();fresh.setItem('danh-grammar-room-v1','new');old.setItem('danh-grammar-room-v1','old');old.clear();assert.equal(fresh.getItem('danh-grammar-room-v1'),'new');});
test('Names are normalized, length limited and never used as storage keys',()=>{assert.equal(C.name('  Hoa   Mai  '),'Hoa Mai');assert.throws(()=>C.name(' '));assert.throws(()=>C.name('a'.repeat(41)));const {store}=fixture(),p=store.create('<img src=x>');assert.equal(p.id,'1');assert.equal(p.name,'<img src=x>');});
